'use client';
import {useEffect,useRef,useState} from 'react';
import {OBJECTS,STAGES,EVIDENCE_KEY,restoreEvidence,inspectEvidence} from './evidence.mjs';
import s from './postcard.module.css';
export default function EvidenceQuest({player,ready,busy,onPause,onHighlight,request,onHandled}){
 const [progress,setProgress]=useState({step:0,seen:[]}),[open,setOpen]=useState(false),[selected,setSelected]=useState(null),[feedback,setFeedback]=useState(''),[hint,setHint]=useState(0),[loaded,setLoaded]=useState(false);const panel=useRef(null);
 useEffect(()=>{try{const raw=localStorage.getItem(EVIDENCE_KEY);setProgress(restoreEvidence(raw));setOpen(!raw);}catch{setOpen(true);}setLoaded(true);},[]);
 useEffect(()=>{onPause(open);if(open&&ready)panel.current?.querySelector('button')?.focus();return()=>onPause(false);},[open,ready,onPause]);
 function inspect(id){if(busy||!player)return;const next=inspectEvidence(progress,id,player);setProgress({step:next.step,seen:next.seen});setFeedback(next.feedback);setSelected(id);setOpen(true);if(next.step!==progress.step){setHint(0);onHighlight(null);}try{localStorage.setItem(EVIDENCE_KEY,JSON.stringify({step:next.step,seen:next.seen}));}catch{}}
 useEffect(()=>{if(request&&loaded){inspect(request);onHandled();}},[request,loaded]);
 const object=player?OBJECTS.find(o=>Math.hypot(o.x-player.x,o.y-player.y)<72):null,stage=STAGES[progress.step],chosen=OBJECTS.find(o=>o.id===selected);
 function close(){setOpen(false);}
 function keys(e){if(e.key==='Escape')close();if(e.key==='Tab'){const items=panel.current.querySelectorAll('button,a'),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
 if(!ready||!loaded)return null;
 return <><div className={s.trail}><button onClick={()=>{setSelected(null);setOpen(true);}}><span>✉</span><div><small>THE PHOTOGRAPH WITHOUT AN ADDRESS</small><strong>{stage.title}</strong></div></button>{object&&<button className={s.inspect} disabled={busy} onClick={()=>inspect(object.id)}>Inspect {object.name} ↗</button>}</div>{open&&<div className={s.scrim} onKeyDown={keys}><section ref={panel} className={s.card} role="dialog" aria-modal="true" aria-label="Evidence notebook"><button className={s.close} onClick={close} aria-label="Close evidence notebook">×</button><small>A FICTIONAL FAMILY STORY · HYDERABAD, CIRCA 1985</small><h2>{chosen?chosen.name:stage.title}</h2>{chosen?<><p>{feedback}</p>{chosen.pattern&&<div style={{display:'flex',gap:15,padding:15}}>{chosen.pattern.map((c,i)=><span key={i} aria-label={c} style={{width:35,height:35,border:`6px double ${c==='green'?'#39705b':c==='red'?'#a84244':c==='blue'?'#477593':'#bb9349'}`,borderRadius:'50%'}}/>)}</div>}{chosen.fact&&<p className={s.fact}>{chosen.fact} <a href={chosen.source} target="_blank" rel="noreferrer">Historical source ↗</a></p>}</>:<p>Someone has torn the address from a family photograph. Find a real scrap beside the chai bench, compare its details with the street, and work out which doorway belongs to the family. Similar objects can lead you astray; every wrong turn has evidence to help you.</p>}<p className={s.clue}><b>Your evidence:</b> {stage.evidence}</p>{progress.step<4&&<><button className={s.quiet} onClick={()=>{const n=Math.min(3,hint+1);setHint(n);if(n===3)onHighlight(stage.target);}}>Need a hint? {hint}/3</button>{hint>0&&<p>{hint===1?stage.evidence:hint===2?stage.district:'The matching object is highlighted in the street. Walk to it and inspect it.'}</p>}</>}<h3>Inspected objects</h3>{progress.seen.length?progress.seen.map(id=><p key={id}><b>{OBJECTS.find(o=>o.id===id).name}</b><br/>{OBJECTS.find(o=>o.id===id).stage>progress.step?'A detail to revisit when you have more evidence.':OBJECTS.find(o=>o.id===id).description}</p>):<p>Your notebook is empty. Start with the chai bench.</p>}<button className={s.go} onClick={close}>{progress.step===4?'Keep wandering':'Back to the street'} →</button></section></div>}</>;
}
