import { ENCOUNTERS } from './encounters.mjs';

import { MOMENTS, sceneOffset } from './reel.mjs';

/** @deprecated Prefer MOMENTS from reel.mjs — kept for timeline labels & lamps. */
export const SCENES = [
  { id: 'square', name: 'Charminar square', subtitle: 'A familiar beginning. An unexpected invitation.', image: '/charminar/timeline-moment-square.png', alt: 'Charminar beyond a busy lane with a chai counter, bangles and an attar shop.', encounters: ['chai', 'bangles', 'attar', 'letter', 'clock'], lamps: [[98,344],[1028,460],[1295,393]], passages: [{ to: 'lane', label: 'Walk into bangle lane' }], event: 'A kettle sighs. Someone has left an invitation at the counter.' },
  { id: 'lane', name: 'Bangle lane', subtitle: 'Follow the colour. Listen between the conversations.', image: '/charminar/timeline-moment-lane.png', alt: 'An intimate illustrated bangle lane, a maroon-clad seller, a parcel runner and a green courtyard entrance.', encounters: ['seller', 'runner', 'radio'], lamps: [[310,390],[1140,370],[780,460]], passages: [{ to: 'square', label: 'Back toward the square' }, { to: 'courtyard', label: 'Through the green arch' }], event: 'Rafi arrives with a parcel. Bashir follows with two cups of chai.' },
  { id: 'courtyard', name: 'The hidden courtyard', subtitle: 'Beyond the green door, the city takes a breath.', image: '/charminar/timeline-moment-courtyard.png', alt: 'A quiet Hyderabad courtyard with a flowering tree, an older woman on a charpoy, a chai seller and a parcel runner.', encounters: ['recipient', 'reunion', 'seal', 'heirloom'], lamps: [[420,350],[1150,380],[780,300]], passages: [{ to: 'lane', label: 'Back through the arch' }], event: 'One by one, the courtyard lamps come on. There is a place for you here.' },
];

export { MOMENTS, sceneOffset };

const added = [
  { id:'letter', scene:'square', number:'04', name:'An invitation without an address', place:'Bashir’s chai counter', object:'The forgotten invitation', x:260,y:570,camera:{x:290,y:570},color:'#CDA45E',icon:'book', invitation:'“You have an eye for old things. Perhaps you can help?”',line:'Bashir slides over an envelope. It is addressed to the keeper of the Moon Bangle House. The shop name is long gone. On the back: a little green door.',action:'Take the invitation',caption:'Inside: “Before the lamps come on. The old courtyard. Bring a friend.”',memory:'An old shop name, a green door, and a reason to keep wandering.',next:'Perhaps someone in bangle lane remembers the Moon Bangle House.'},
  { id:'seller',scene:'lane',number:'05',name:'The name above the shop',place:'Zehra’s bangle stall',object:'A name remembered',x:390,y:650,camera:{x:420,y:630},color:'#C7796C',icon:'bangle',invitation:'“Moon Bangle House? Now there is a name I have not heard in years.”',line:'Zehra recognises the envelope. “That was Amina’s shop. Look for the green arch with a brass crescent. Rafi is taking a parcel there.”',action:'Ask about Amina',caption:'Zehra turns a green bangle in her hand. “She always chose this colour: Emerald Green, Pomegranate Red, Emerald Green.”',memory:'Zehra remembers Amina, the old shop, and the secret green-red-green lacquer bangle sequence.',next:'Find Rafi, the runner carrying a cloth parcel.'},
  { id:'runner',scene:'lane',number:'06',name:'Someone knows the way',place:'Rafi’s delivery stop',object:'The crescent above the door',x:1170,y:670,camera:{x:1160,y:650},color:'#CDA45E',icon:'compass',invitation:'“Amina aunty? I am going there. You can walk with me.”',line:'Rafi points up at the brass crescent. “Everyone knows the courtyard. We just forget to look through the door.” Bashir passes behind him, balancing two cups.',action:'Follow Rafi’s directions',caption:'The green arch is open. Beyond it, you hear cups being set down.',memory:'A brass crescent above a green arch. A familiar face carrying chai.',next:'Step through the green arch into the courtyard.'},
  { id:'recipient',scene:'courtyard',number:'07',name:'You found your way',place:'Amina’s charpoy',object:'An invitation delivered',x:1130,y:665,camera:{x:1090,y:650},color:'#97A58A',icon:'book',invitation:'“I wondered who would bring it this year.”',line:'Amina smiles at the old shop name. “The shop closed. The evening did not.” She wrote the invitation for whoever was curious enough to follow it. Rafi leaves his parcel: a box of bangles.',action:'Give Amina the invitation',caption:'“Sit. Bashir has brought enough chai.” The invitation was for you, too.',memory:'The keeper of the old shop had been saving a place for a new friend.',next:'Bashir is here with the chai. Stay for the evening.'},
  { id:'reunion',scene:'courtyard',number:'08',name:'One more place at the table',place:'Chai with Bashir',object:'A place in the courtyard',x:450,y:690,camera:{x:460,y:650},color:'#CDA45E',icon:'cup',invitation:'“I said there was room for one more.”',line:'Bashir hands you a cup. Amina opens the bangles. Rafi settles on the steps. From here, the bazaar is only a distant murmur. A strange address has become a familiar place.',action:'Stay for the evening',caption:'No more directions. Just a warm cup, the lamps, and a little company.',memory:'You followed an invitation through three places and found a place of your own.',next:'The story is complete. The neighbourhood is still yours to wander.'},
  { id:'clock',scene:'square',number:'09',name:'The 1889 Vulliamy Clockworks',place:'Charminar Clock Tower',object:'The 1889 Dial (Lock 2 Clue)',x:768,y:220,camera:{x:768,y:350},color:'#D97706',icon:'compass',invitation:'“Four faces looking toward the four corners of the kingdom.”',line:'Installed in 1889 by Vulliamy & Co. of London during Nizam VI’s reign, the giant clock hands point to 4:45 PM—the chime of the evening bazaar.',action:'Record Clock Clue',caption:'Cipher 2 Clue: Set the Heirloom Box clock hands to 4:45 PM.',memory:'The giant 1889 clock dials of Charminar frozen at 4:45 PM.',next:'Check Zehra’s bangles in bangle lane for the first cipher.'},
  { id:'radio',scene:'lane',number:'10',name:'Akashvani Broadcast Band',place:'Salim’s Radio Repair',object:'Vintage Radio (Lock 3 Clue)',x:820,y:520,camera:{x:820,y:500},color:'#B45309',icon:'sound',invitation:'“Deccan Radio was broadcasting right from these quarters.”',line:'The glowing green magic eye tuning tube locks sharply onto Medium Wave 880 kHz (Akashvani Hyderabad). Classical ghazals drift into the alley.',action:'Record Radio Clue',caption:'Cipher 3 Clue: Slide the Heirloom Box radio tuner to 880 kHz.',memory:'Akashvani Hyderabad tuned at 880 kHz with a bright green tuning eye.',next:'Pass through the green arch into the courtyard to find the crescent seal.'},
  { id:'seal',scene:'courtyard',number:'11',name:'Asaf Jahi Imperial Medallion',place:'The Courtyard Arch',object:'Carved Crescent (Lock 4 Clue)',x:930,y:400,camera:{x:930,y:420},color:'#C2603A',icon:'compass',invitation:'“Notice how the crescent moon above the arch is carved.”',line:'The brass medallion above the green archway shows the Asaf Jahi crescent with horns facing to the right (90° East), welcoming morning light.',action:'Record Seal Clue',caption:'Cipher 4 Clue: Rotate the Heirloom Box crescent medallion to face RIGHT (East).',memory:'An Asaf Jahi crescent seal carved with horns pointing right.',next:'Inspect the Heirloom Box resting on the courtyard table!'},
  { id:'heirloom',scene:'courtyard',number:'12',name:'The Nizam’s Lost Heirloom Box',place:'Amina’s Antique Table',object:'4-Cipher Heirloom Box',x:740,y:640,camera:{x:740,y:620},color:'#8B3A1A',icon:'book',invitation:'“The heirloom box has waited decades under the flowering tree.”',line:'A heavy brass-bound Asaf Jahi jewelry box fitted with four mechanical cipher locks: lacquer bangle rings, clock dials, radio slider, and crescent seal.',action:'Inspect the Heirloom Box',caption:'Crack all 4 ciphers using clues from Charminar to claim the Royal Basra Pearl!',memory:'The Nizam’s Lost Heirloom Box found in the hidden courtyard.',next:'Inspect each cipher lock and input your deductions!'}
];

export const ALL_ENCOUNTERS = [...ENCOUNTERS.map(e=>({...e,scene:'square'})),...added];
export const STORY = [
  {id:'letter',title:'The forgotten invitation',hint:'Bashir has an envelope at his chai counter.',scene:'square'},
  {id:'seller',title:'A name remembered',hint:'Ask Zehra in bangle lane about the old shop name.',scene:'lane'},
  {id:'runner',title:'The green arch',hint:'Find Rafi and his parcel in bangle lane.',scene:'lane'},
  {id:'recipient',title:'The keeper of the shop',hint:'Amina is waiting in the hidden courtyard.',scene:'courtyard'},
  {id:'reunion',title:'A place for you',hint:'Bashir has brought the chai. Stay a while.',scene:'courtyard'},
];

export function storyStage(memories) {
  const missing = STORY.findIndex(step=>!memories.includes(step.id));
  return missing < 0 ? STORY.length : missing;
}

export function resolveEncounter(item, memories) {
  if (!item) return null;
  const index = STORY.findIndex(step=>step.id===item.id);
  const stage = storyStage(memories);
  if (index <= stage || index < 0) return item;
  return {...item, locked:true, invitation: index > 2 ? '“Come in. There is no need to stand at the door.”' : '“Take your time. There is plenty to look at.”', line: index > 2 ? 'The courtyard welcomes you, but the envelope has a story you have not heard yet. Follow the invitation to find out how these neighbours know one another.' : 'You can explore freely. To ask about the invitation, first follow the thread from Bashir’s counter.', action:'Follow the invitation',next:STORY[stage].hint};
}
